os: osx
language: rust
rust: stable
if: branch != master OR type != push
matrix:
  include:
    # macOS 10.11
    - osx_image: xcode7.3
      env: TARGET=x86_64-apple-darwin CGFEATURES=""
    # macOS 10.12
    - osx_image: xcode9.2
      env: TARGET=x86_64-apple-darwin CGFEATURES="--features elcapitan"
    # macOS 10.13
    - osx_image: xcode9.4
      env: TARGET=x86_64-apple-darwin CGFEATURES="--features highsierra,elcapitan"
    # macOS 10.14
    - osx_image: xcode11.3
      env: TARGET=x86_64-apple-darwin CGFEATURES="--features highsierra,elcapitan"

install:
  - rustup target add $TARGET
script:
  - cargo build --all-targets --verbose --target $TARGET
  - cargo test --verbose --target $TARGET -- --nocapture
