[package]
name = "sycamore-zest"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zest = { path = "../../../rui/crates/zest" }
sycamore-core = { path = "../sycamore-core", version = "0.8.0" }
sycamore-reactive = { path = "../sycamore-reactive", version = "0.8.0" }
