[package]
name = "memoize_attr"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.0", features = ["full"] }
quote = "1.0"


[lib]
proc-macro = true
